R: 1
G: 4
P: 2
L: 3
N: 3
seed: 123
agent_config:
  beta_teacher: 1.0
  beta_evo: 1.0
  learn_d: true
  agent_types:
    - human
    - machine
  T:
    - 10
    - 1000
  d:
    - 1
    - 3
  eps:
    - 1.0
    - 1.0
  phi:
    - 0.5
    - 0.5
  N_0:
    - 3
    - 0
  N_o:
    - 3
    - 0
task_config:
  strategies:
    - "111"
  strategy_distribution: fixed
  r_safe: null
  c_cost: 1.0
  r_scale: 1.0
  lam: 3
  p_applicable: 0.5
  mode: sparse
  alpha: 2.0
  gamma: 1.0